[package]
name = "game-settings"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
bevy.workspace = true
humantime.workspace = true
serde.workspace = true
thiserror.workspace = true
toml.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
