[package]
name = "game"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false
autobenches = false

[features]
default = []
dim2 = ["bevy/2d", "game-physics/dim2", "bevy_hanabi?/2d"]
dim3 = ["bevy/3d", "game-physics/dim3", "bevy_hanabi?/3d"]
networked = ["dep:lightyear", "dep:bevy_enhanced_input", "dep:bevy_hanabi", "dep:serde", "dep:thiserror", "game-physics/networked"]
mcp = ["dep:bevy_brp_extras", "dep:bevy-inspector-egui", "bevy/bevy_remote", "bevy/sysinfo_plugin"]
web = ["bevy/webgl2"]
dev = ["bevy/dev"]
dynamic_linking = ["bevy/dynamic_linking"]
trace_chrome = ["bevy/trace_chrome"]
trace_tracy = ["bevy/trace_tracy"]

[dependencies]
bevy.workspace = true
bevy_enhanced_input = { workspace = true, optional = true }
game-physics.workspace = true
game-settings.workspace = true
lightyear = { workspace = true, optional = true }
serde = { workspace = true, optional = true }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
bevy-inspector-egui = { workspace = true, optional = true }
bevy_brp_extras = { workspace = true, optional = true }
bevy_hanabi = { workspace = true, optional = true }
thiserror = { workspace = true, optional = true }

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "simulation"
harness = false
required-features = ["networked"]

[[test]]
name = "network_demo"
required-features = ["networked"]

[lints]
workspace = true
